[variables]
NODE_ENV = "production"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["cd backend && npm install --omit=optional"]

[phases.build]
cmds = ["cd backend && npm run db:generate"]

[start]
cmd = "cd backend && npm start"
